<?php

use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        $permissions=[
            [
            "id"=>1,
            "name"=>"category.index"
        ],[
            "id"=>2,
            "name"=>"category.create"
        ],[
            "id"=>3,
            "name"=>"category.edit"
        ],[
            "id"=>4,
            "name"=>"category.destroy"
        ],[
            "id"=>5,
            "name"=>"brand.index"
        ],[
            "id"=>6,
            "name"=>"brand.create"
        ],[
            "id"=>7,
            "name"=>"brand.edit"
        ],[
            "id"=>8,
            "name"=>"brand.destroy"
        ],[
            "id"=>9,
            "name"=>"attribute-set.index"
        ],[
            "id"=>10,
            "name"=>"attribute-set.create"
        ],[
            "id"=>11,
            "name"=>"attribute-set.edit"
        ],[
            "id"=>12,
            "name"=>"attribute-set.destroy"
        ],[
            "id"=>13,
            "name"=>"badge.index"
        ],[
            "id"=>14,
            "name"=>"badge.create"
        ],[
            "id"=>15,
            "name"=>"badge.edit"
        ],[
            "id"=>16,
            "name"=>"badge.destroy"
        ],[
            "id"=>17,
            "name"=>"coupon.index"
        ],[
            "id"=>18,
            "name"=>"coupon.create"
        ],[
            "id"=>19,
            "name"=>"coupon.edit"
        ],[
            "id"=>20,
            "name"=>"coupon.destroy"
        ],[
            "id"=>21,
            "name"=>"currency.index"
        ],[
            "id"=>22,
            "name"=>"currency.create"
        ],[
            "id"=>23,
            "name"=>"currency.edit"
        ],[
            "id"=>24,
            "name"=>"currency.destroy"
        ],[
            "id"=>25,
            "name"=>"flash-sale.index"
        ],[
            "id"=>26,
            "name"=>"flash-sale.create"
        ],[
            "id"=>27,
            "name"=>"flash-sale.edit"
        ],[
            "id"=>28,
            "name"=>"flash-sale.destroy"
        ],[
            "id"=>29,
            "name"=>"page.index"
        ],[
            "id"=>30,
            "name"=>"page.create"
        ],[
            "id"=>31,
            "name"=>"page.edit"
        ],[
            "id"=>32,
            "name"=>"page.destroy"
        ],[
            "id"=>33,
            "name"=>"report.index"
        ],[
            "id"=>34,
            "name"=>"setting.edit"
        ],[
            "id"=>35,
            "name"=>"slide.index"
        ],[
            "id"=>36,
            "name"=>"slide.create"
        ],[
            "id"=>37,
            "name"=>"slide.edit"
        ],[
            "id"=>38,
            "name"=>"slide.destroy"
        ],[
            "id"=>39,
            "name"=>"tag.index"
        ],[
            "id"=>40,
            "name"=>"tag.create"
        ],[
            "id"=>41,
            "name"=>"tag.edit"
        ],[
            "id"=>42,
            "name"=>"tag.destroy"
        ],[
            "id"=>43,
            "name"=>"translation.index"
        ],[
            "id"=>44,
            "name"=>"translation.create"
        ],[
            "id"=>45,
            "name"=>"translation.edit"
        ],[
            "id"=>46,
            "name"=>"translation.destroy"
        ],[
            "id"=>47,
            "name"=>"user.index"
        ],[
            "id"=>48,
            "name"=>"user.create"
        ],[
            "id"=>49,
            "name"=>"user.edit"
        ],[
            "id"=>50,
            "name"=>"user.destroy"
        ],[
            "id"=>51,
            "name"=>"blog.index"
        ],[
            "id"=>52,
            "name"=>"blog.create"
        ],[
            "id"=>53,
            "name"=>"blog.edit"
        ],[
            "id"=>54,
            "name"=>"blog.destroy"
        ],[
            "id"=>55,
            "name"=>"attribute.index"
        ],[
            "id"=>56,
            "name"=>"attribute.create"
        ],[
            "id"=>57,
            "name"=>"attribute.edit"
        ],[
            "id"=>58,
            "name"=>"attribute.destroy"
        ],[
            "id"=>59,
            "name"=>"sub-category.index"
        ],[
            "id"=>60,
            "name"=>"sub-category.create"
        ],[
            "id"=>61,
            "name"=>"sub-category.edit"
        ],[
            "id"=>62,
            "name"=>"sub-category.destroy"
        ],[
            "id"=>63,
            "name"=>"child-category.index"
        ],[
            "id"=>64,
            "name"=>"child-category.create"
        ],[
            "id"=>65,
            "name"=>"child-category.edit"
        ],[
            "id"=>66,
            "name"=>"child-category.destroy"
        ],[
            "id"=>67,
            "name"=>"category.update"
        ],[
            "id"=>68,
            "name"=>"sub-category.update"
        ],[
            "id"=>69,
            "name"=>"child-category.update"
        ],[
            "id"=>70,
            "name"=>"brand.update"
        ],[
            "id"=>71,
            "name"=>"attribute.update"
        ],[
            "id"=>72,
            "name"=>"badge.update"
        ],[
            "id"=>73,
            "name"=>"coupon.update"
        ],[
            "id"=>74,
            "name"=>"currency.update"
        ],[
            "id"=>75,
            "name"=>"flash-sale.update"
        ],[
            "id"=>76,
            "name"=>"page.update"
        ],[
            "id"=>77,
            "name"=>"setting.update"
        ],[
            "id"=>78,
            "name"=>"slide.update"
        ],[
            "id"=>79,
            "name"=>"tag.update"
        ],[
            "id"=>80,
            "name"=>"translation.update"
        ],[
            "id"=>81,
            "name"=>"user.update"
        ],[
            "id"=>82,
            "name"=>"blog.update"
        ],[
            "id"=>83,
            "name"=>"attribute-set.update"
        ],[
            "id"=>84,
            "name"=>"category.store"
        ],[
            "id"=>85,
            "name"=>"sub-category.store"
        ],[
            "id"=>86,
            "name"=>"child-category.store"
        ],[
            "id"=>87,
            "name"=>"brand.store"
        ],[
            "id"=>88,
            "name"=>"attribute.store"
        ],[
            "id"=>89,
            "name"=>"badge.store"
        ],[
            "id"=>90,
            "name"=>"coupon.store"
        ],[
            "id"=>91,
            "name"=>"currency.store"
        ],[
            "id"=>92,
            "name"=>"flash-sale.store"
        ],[
            "id"=>93,
            "name"=>"page.store"
        ],[
            "id"=>94,
            "name"=>"slide.store"
        ],[
            "id"=>95,
            "name"=>"tag.store"
        ],[
            "id"=>96,
            "name"=>"translation.store"
        ],[
            "id"=>97,
            "name"=>"user.store"
        ],[
            "id"=>98,
            "name"=>"blog.store"
        ],[
            "id"=>99,
            "name"=>"attribute-set.store"
        ],[
            "id"=>100,
            "name"=>"role.index"
        ],[
            "id"=>101,
            "name"=>"role.create"
        ],[
            "id"=>102,
            "name"=>"role.edit"
        ],[
            "id"=>103,
            "name"=>"role.destroy"
        ],[
            "id"=>104,
            "name"=>"role.store"
        ],[
            "id"=>105,
            "name"=>"role.update"
        ],[
            "id"=>106,
            "name"=>"product.index"
        ],[
            "id"=>107,
            "name"=>"product.create"
        ],[
            "id"=>108,
            "name"=>"product.edit"
        ],[
            "id"=>109,
            "name"=>"product.destroy"
        ],[
            "id"=>110,
            "name"=>"product.store"
        ],[
            "id"=>111,
            "name"=>"product.update"
        ],[
            "id"=>112,
            "name"=>"order.index"
        ],[
            "id"=>113,
            "name"=>"order.show"
        ],[
            "id"=>114,
            "name"=>"order.edit"
        ],[
            "id"=>115,
            "name"=>"order.destroy"
        ],[
            "id"=>116,
            "name"=>"order.update"
        ],[
            "id"=>117,
            "name"=>"color.index"
        ],[
            "id"=>118,
            "name"=>"color.create"
        ],[
            "id"=>119,
            "name"=>"color.edit"
        ],[
            "id"=>120,
            "name"=>"color.destroy"
        ],[
            "id"=>121,
            "name"=>"color.store"
        ],[
            "id"=>122,
            "name"=>"color.update"
        ],[
            "id"=>123,
            "name"=>"size.index"
        ],[
            "id"=>124,
            "name"=>"size.create"
        ],[
            "id"=>125,
            "name"=>"size.edit"
        ],[
            "id"=>126,
            "name"=>"size.destroy"
        ],[
            "id"=>127,
            "name"=>"size.store"
        ],[
            "id"=>128,
            "name"=>"size.update"
        ],[
            "id"=>129,
            "name"=>"faq.index"
        ],[
            "id"=>130,
            "name"=>"faq.create"
        ],[
            "id"=>131,
            "name"=>"faq.edit"
        ],[
            "id"=>132,
            "name"=>"faq.destroy"
        ],[
            "id"=>133,
            "name"=>"faq.store"
        ],[
            "id"=>134,
            "name"=>"faq.update"
        ],[
            "id"=>135,
            "name"=>"ticket-category.index"
        ],[
            "id"=>136,
            "name"=>"ticket-category.create"
        ],[
            "id"=>137,
            "name"=>"ticket-category.edit"
        ],[
            "id"=>138,
            "name"=>"ticket-category.destroy"
        ],[
            "id"=>139,
            "name"=>"ticket-category.store"
        ],[
            "id"=>140,
            "name"=>"ticket-category.update"
        ],[
            "id"=>141,
            "name"=>"ticket.index"
        ],[
            "id"=>142,
            "name"=>"ticket.create"
        ],[
            "id"=>143,
            "name"=>"ticket.edit"
        ],[
            "id"=>144,
            "name"=>"ticket.destroy"
        ],[
            "id"=>145,
            "name"=>"ticket.store"
        ],[
            "id"=>146,
            "name"=>"ticket.update"
        ],[
            "id"=>147,
            "name"=>"affiliate.index"
        ],[
            "id"=>148,
            "name"=>"affiliate.create"
        ],[
            "id"=>149,
            "name"=>"affiliate.edit"
        ],[
            "id"=>150,
            "name"=>"affiliate.destroy"
        ],[
            "id"=>151,
            "name"=>"affiliate.store"
        ],[
            "id"=>152,
            "name"=>"affiliate.update"
        ],[
            "id"=>153,
            "name"=>"language.index"
        ],[
            "id"=>154,
            "name"=>"language.show"
        ],[
            "id"=>155,
            "name"=>"language.create"
        ],[
            "id"=>156,
            "name"=>"language.edit"
        ],[
            "id"=>157,
            "name"=>"language.destroy"
        ],[
            "id"=>158,
            "name"=>"language.store"
        ],[
            "id"=>159,
            "name"=>"language.update"
        ],[
            "id"=>160,
            "name"=>"shipping-method.index"
        ],[
            "id"=>161,
            "name"=>"shipping-method.show"
        ],[
            "id"=>162,
            "name"=>"shipping-method.create"
        ],[
            "id"=>163,
            "name"=>"shipping-method.edit"
        ],[
            "id"=>164,
            "name"=>"shipping-method.destroy"
        ],[
            "id"=>165,
            "name"=>"shipping-method.store"
        ],[
            "id"=>166,
            "name"=>"shipping-method.update"
        ],[
            "id"=>167,
            "name"=>"review.index"
        ],[
            "id"=>168,
            "name"=>"review.show"
        ],[
            "id"=>169,
            "name"=>"review.create"
        ],[
            "id"=>170,
            "name"=>"review.edit"
        ],[
            "id"=>171,
            "name"=>"review.destroy"
        ],[
            "id"=>172,
            "name"=>"review.store"
        ],[
            "id"=>173,
            "name"=>"review.update"
        ],[
            "id"=>174,
            "name"=>"payment-gateway.index"
        ],[
            "id"=>175,
            "name"=>"payment-gateway.create"
        ],[
            "id"=>176,
            "name"=>"payment-gateway.edit"
        ],[
            "id"=>177,
            "name"=>"payment-gateway.destroy"
        ],[
            "id"=>178,
            "name"=>"payment-gateway.store"
        ],[
            "id"=>179,
            "name"=>"payment-gateway.update"
        ],[
            "id"=>180,
            "name"=>"customer.index"
        ],[
            "id"=>181,
            "name"=>"customer.update"
        ],[
            "id"=>182,
            "name"=>"withdraw.index"
        ],[
            "id"=>183,
            "name"=>"withdraw.update"
        ],[
            "id"=>184,
            "name"=>"customer.destroy"
        ],[
            "id"=>185,
            "name"=>"withdraw.destroy"
        ]
        ,[
            "id"=>186,
            "name"=>"comment.index"
        ]
        ,[
            "id"=>187,
            "name"=>"comment.destroy"
        ]
    ]; 
        foreach($permissions as $permission){
            DB::table('permissions')->insert($permission);
        }
    }
}
